server:
  port: ${SERVER_PORT:11111}

spring:
  application:
    name: ${APPLICATION_NAME:client-service}
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://cockroach:26257/defaultdb?enabledTLSProtocols=TLSv1.2&ssl=true&sslmode=require&sslrootcert=C:\SourceCode\btsd\projects\experiments\springMicroserviceEcosystem\.cockroach-certs\ca.crt&sslkey=C:\SourceCode\btsd\projects\experiments\springMicroserviceEcosystem\.cockroach-certs\client.root.pk8&sslcert=C:\SourceCode\btsd\projects\experiments\springMicroserviceEcosystem\.cockroach-certs\client.root.crt
    username: root
  liquibase:
    changeLog: "classpath:db/changelog/db.changelog-master.yaml"

#For curl localhost:9988/actuator/refresh -d {} -H "Content-Type: application/json"
management:
  endpoints:
    web:
      exposure:
        include=*:

eureka:
  instance:
    hostname: ${HOST_NAME:client-service-1.com}
    homePageUrl: http://${eureka.instance.hostname}/
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://discovery-service-1.com:8761/eureka/}

logging.level:
  com.fdobrotv: trace
  "liquibase" : info
