apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service
spec:
  selector:
    matchLabels:
      app: client-service
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: client-service
    spec:
      containers:
        - name: client-service
          image: {{ .Values.image.name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.app.profile }}
            - name: DB_HOST
              value: {{ .Values.app.dbHost }}
            - name: CONFIGURATION_SERVICE_HOST
              value: {{ .Values.app.configurationServiceHost }}
            - name: TRACING_SERVICE_HOST
              value: {{ .Values.app.tracingServiceHost }}
            - name: SERVER_PORT
              value: {{ .Values.containerPort | quote }} # containerPort is integer, but env expects string
            - name: APPLICATION_NAME
              value: {{ .Values.app.name }}
